#!/bin/sh
exec 2>&1

RUN_FILE="$(readlink -f "$0")"
SCRIPT_DIR="$(dirname "$(dirname "$(dirname "$RUN_FILE")")")"
SERVICE_NAME="$(basename "$SCRIPT_DIR")"
exec multilog t s153600 n3 "/var/log/$SERVICE_NAME"
